<#
.SYNOPSIS
Checks that each C# source file contains one matching top-level named type.

.DESCRIPTION
Uses the Roslyn parser from the installed .NET SDK. Existing violations may be
recorded in config/ai-repo-workflow/csharp-source-layout-allowance.jsonc. An
allowance permits only the declarations already recorded for that file; adding
another declaration still fails. Use -WriteAllowance only for an explicit
one-time migration.
#>

[CmdletBinding(SupportsShouldProcess = $true)]
param(
    [Parameter()]
    [string] $RepoRoot,

    [Parameter()]
    [string] $AllowancePath = "config/ai-repo-workflow/csharp-source-layout-allowance.jsonc",

    [Parameter()]
    [switch] $WriteAllowance
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

if ([string]::IsNullOrWhiteSpace($RepoRoot)) {
    $RepoRoot = Split-Path -Path $PSScriptRoot -Parent
}

$repoRootFull = [System.IO.Path]::GetFullPath($RepoRoot)
if (-not (Test-Path -LiteralPath $repoRootFull -PathType Container)) {
    throw "Repository root does not exist: $repoRootFull"
}

function Get-CSharpLayoutRelativePath {
    param(
        [Parameter(Mandatory)] [string] $RootPath,
        [Parameter(Mandatory)] [string] $FullPath
    )

    $root = [System.IO.Path]::GetFullPath($RootPath).TrimEnd([System.IO.Path]::DirectorySeparatorChar, [System.IO.Path]::AltDirectorySeparatorChar)
    $rootUri = [System.Uri]::new($root + [System.IO.Path]::DirectorySeparatorChar)
    $fileUri = [System.Uri]::new([System.IO.Path]::GetFullPath($FullPath))
    return [System.Uri]::UnescapeDataString($rootUri.MakeRelativeUri($fileUri).ToString()).Replace('\\', '/').Replace('\', '/')
}

function Test-CSharpGeneratedFile {
    param([Parameter(Mandatory)] [System.IO.FileInfo] $File)

    if ($File.Name -match '(?i)\.(g|generated|designer)\.cs$') { return $true }
    if ($File.FullName -match '(?i)[\\/](bin|obj)[\\/]') { return $true }

    $reader = [System.IO.File]::OpenText($File.FullName)
    try {
        for ($lineNumber = 0; $lineNumber -lt 8 -and -not $reader.EndOfStream; $lineNumber++) {
            if ($reader.ReadLine() -match '(?i)<auto-generated') { return $true }
        }
    }
    finally {
        $reader.Dispose()
    }

    return $false
}

function Get-CSharpSourceFiles {
    param([Parameter(Mandatory)] [string] $RootPath)

    return @(Get-ChildItem -LiteralPath $RootPath -File -Recurse -Filter '*.cs' -Force |
        Where-Object {
            $relative = Get-CSharpLayoutRelativePath -RootPath $RootPath -FullPath $_.FullName
            $relative -notmatch '^(?i)(\.git|bin|obj|downloads|snapshots|artifacts/diagnostics)/' -and
            $relative -notmatch '(?i)/(bin|obj)/' -and
            -not (Test-CSharpGeneratedFile -File $_)
        } |
        Sort-Object FullName)
}

function Import-RoslynAssemblies {
    $dotnetCommand = Get-Command dotnet -ErrorAction SilentlyContinue
    if ($null -eq $dotnetCommand) {
        throw 'C# source files were found, but the .NET SDK was not available. Install a .NET SDK so source-layout verification can use Roslyn.'
    }

    $sdkLines = @(& $dotnetCommand.Source --list-sdks 2>&1)
    if ($LASTEXITCODE -ne 0 -or $sdkLines.Count -eq 0) {
        throw 'C# source files were found, but `dotnet --list-sdks` returned no usable SDK.'
    }

    $sdks = foreach ($line in $sdkLines) {
        if ($line -match '^\s*(?<version>[^\s]+)\s+\[(?<root>.+)\]\s*$') {
            $versionText = $matches.version
            $numericVersionText = ($versionText -replace '-.*$', '')
            $version = $null
            if ([System.Version]::TryParse($numericVersionText, [ref] $version)) {
                [pscustomobject]@{
                    Version = $version
                    VersionText = $versionText
                    Root = $matches.root
                }
            }
        }
    }

    $selected = @($sdks | Sort-Object Version -Descending | Select-Object -First 1)
    if ($selected.Count -eq 0) {
        throw 'Could not parse any installed .NET SDK paths from `dotnet --list-sdks`.'
    }

    $roslynRoot = Join-Path -Path (Join-Path -Path $selected[0].Root -ChildPath $selected[0].VersionText) -ChildPath 'Roslyn/bincore'
    $codeAnalysisPath = Join-Path -Path $roslynRoot -ChildPath 'Microsoft.CodeAnalysis.dll'
    $csharpPath = Join-Path -Path $roslynRoot -ChildPath 'Microsoft.CodeAnalysis.CSharp.dll'
    foreach ($path in @($codeAnalysisPath, $csharpPath)) {
        if (-not (Test-Path -LiteralPath $path -PathType Leaf)) {
            throw "Roslyn parser assembly was not found in the selected .NET SDK: $path"
        }
    }

    if ($null -eq ('Microsoft.CodeAnalysis.SyntaxTree' -as [type])) {
        [void] [System.Reflection.Assembly]::LoadFrom($codeAnalysisPath)
    }
    $loadedCSharpType = 'Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree' -as [type]
    $csharpAssembly = if ($null -eq $loadedCSharpType) {
        [System.Reflection.Assembly]::LoadFrom($csharpPath)
    }
    else {
        $loadedCSharpType.Assembly
    }

    $script:CSharpSyntaxTreeType = $csharpAssembly.GetType('Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree', $true)
    $parseTextMethod = $script:CSharpSyntaxTreeType.GetMethods([System.Reflection.BindingFlags]::Public -bor [System.Reflection.BindingFlags]::Static) |
        Where-Object {
            $_.Name -eq 'ParseText' -and
            $_.GetParameters().Count -eq 5 -and
            $_.GetParameters()[0].ParameterType -eq [string]
        } |
        Select-Object -First 1
    if ($null -eq $parseTextMethod) {
        throw 'Could not resolve the Roslyn CSharpSyntaxTree.ParseText(string, ...) method.'
    }
    $script:CSharpParseTextMethod = $parseTextMethod.PSObject.BaseObject

    $syntaxTreeType = 'Microsoft.CodeAnalysis.SyntaxTree' -as [type]
    if ($null -eq $syntaxTreeType) {
        throw 'Could not resolve the Roslyn SyntaxTree type.'
    }
    $getRootMethod = $syntaxTreeType.GetMethods([System.Reflection.BindingFlags]::Public -bor [System.Reflection.BindingFlags]::Instance) |
        Where-Object {
            $_.Name -eq 'GetRoot' -and
            $_.GetParameters().Count -eq 1 -and
            $_.GetParameters()[0].ParameterType -eq [System.Threading.CancellationToken]
        } |
        Select-Object -First 1
    if ($null -eq $getRootMethod) {
        throw 'Could not resolve the Roslyn SyntaxTree.GetRoot(CancellationToken) method.'
    }
    $script:SyntaxTreeGetRootMethod = $getRootMethod.PSObject.BaseObject
}

function Get-TopLevelCSharpDeclarations {
    param([Parameter(Mandatory)] $Members)

    $result = [System.Collections.Generic.List[object]]::new()
    foreach ($member in $Members) {
        $memberObject = $member.PSObject.BaseObject
        $memberTypeName = $memberObject.GetType().FullName
        if ($memberTypeName -eq 'Microsoft.CodeAnalysis.CSharp.Syntax.NamespaceDeclarationSyntax' -or
            $memberTypeName -eq 'Microsoft.CodeAnalysis.CSharp.Syntax.FileScopedNamespaceDeclarationSyntax') {
            foreach ($nested in @(Get-TopLevelCSharpDeclarations -Members $memberObject.Members)) {
                $result.Add($nested)
            }
            continue
        }

        $kind = switch ($memberTypeName) {
            'Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax' { 'class'; break }
            'Microsoft.CodeAnalysis.CSharp.Syntax.RecordDeclarationSyntax' { 'record'; break }
            'Microsoft.CodeAnalysis.CSharp.Syntax.StructDeclarationSyntax' { 'struct'; break }
            'Microsoft.CodeAnalysis.CSharp.Syntax.InterfaceDeclarationSyntax' { 'interface'; break }
            'Microsoft.CodeAnalysis.CSharp.Syntax.EnumDeclarationSyntax' { 'enum'; break }
            'Microsoft.CodeAnalysis.CSharp.Syntax.DelegateDeclarationSyntax' { 'delegate'; break }
            default { $null }
        }
        if ($null -eq $kind) { continue }

        $isPartial = $false
        if ($memberObject.PSObject.Properties.Name -contains 'Modifiers') {
            foreach ($modifier in $memberObject.Modifiers) {
                $modifierObject = $modifier.PSObject.BaseObject
                if ($modifierObject.Text -eq 'partial') { $isPartial = $true; break }
            }
        }

        $identifier = $memberObject.Identifier.ValueText
        $result.Add([pscustomobject]@{
            Kind = $kind
            Name = $identifier
            IsPartial = $isPartial
            Fingerprint = "$kind`:$identifier"
        })
    }

    return @($result)
}

function Test-CSharpDeclarationFileName {
    param(
        [Parameter(Mandatory)] [string] $FileName,
        [Parameter(Mandatory)] $Declaration
    )

    if ($FileName -ieq "$($Declaration.Name).cs") { return $true }
    if ($Declaration.IsPartial -and $FileName -imatch ('^' + [regex]::Escape($Declaration.Name) + '\.[^.]+(?:\.[^.]+)*\.cs$')) { return $true }
    return $false
}

function Get-CSharpLayoutViolations {
    param(
        [Parameter(Mandatory)] [string] $RootPath,
        [Parameter(Mandatory)] [System.IO.FileInfo[]] $Files
    )

    $violations = [System.Collections.Generic.List[object]]::new()
    foreach ($file in $Files) {
        $text = Get-Content -LiteralPath $file.FullName -Raw
        $parseArguments = [System.Object[]]::new(5)
        $parseArguments[0] = ([string] $text).PSObject.BaseObject
        $parseArguments[1] = $null
        $parseArguments[2] = [string]::Empty
        $parseArguments[3] = $null
        $parseArguments[4] = [System.Threading.CancellationToken]::None
        $tree = $script:CSharpParseTextMethod.Invoke($null, $parseArguments)
        $treeObject = $tree.PSObject.BaseObject
        $rootArguments = [System.Object[]]::new(1)
        $rootArguments[0] = [System.Threading.CancellationToken]::None
        $root = $script:SyntaxTreeGetRootMethod.Invoke($treeObject, $rootArguments)
        $rootObject = $root.PSObject.BaseObject
        $declarations = @(Get-TopLevelCSharpDeclarations -Members $rootObject.Members)
        if ($declarations.Count -eq 0) { continue }

        $hasFileNameMismatch = @($declarations | Where-Object { -not (Test-CSharpDeclarationFileName -FileName $file.Name -Declaration $_) }).Count -gt 0
        if ($declarations.Count -le 1 -and -not $hasFileNameMismatch) { continue }

        $violations.Add([pscustomobject]@{
            Path = Get-CSharpLayoutRelativePath -RootPath $RootPath -FullPath $file.FullName
            Declarations = @($declarations | ForEach-Object { $_.Fingerprint } | Sort-Object)
            HasFileNameMismatch = $hasFileNameMismatch
        })
    }

    return @($violations)
}

function Read-CSharpLayoutAllowance {
    param([Parameter(Mandatory)] [string] $Path)

    if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) { return @{} }
    $text = Get-Content -LiteralPath $Path -Raw
    $text = [regex]::Replace($text, '(?m)//.*$', '')
    if ([string]::IsNullOrWhiteSpace($text)) { return @{} }
    $document = $text | ConvertFrom-Json -Depth 32
    if ($null -eq $document -or $document.schemaVersion -ne 1) {
        throw "Unsupported C# source-layout allowance schema: $Path"
    }

    $lookup = @{}
    foreach ($entry in @($document.files)) {
        $lookup[[string] $entry.path] = $entry
    }
    return $lookup
}

function Test-CSharpViolationAllowed {
    param(
        [Parameter(Mandatory)] $Violation,
        [Parameter(Mandatory)] $Allowance
    )

    $allowedCounts = @{}
    foreach ($declaration in @($Allowance.declarations)) {
        $key = [string] $declaration
        if (-not $allowedCounts.ContainsKey($key)) { $allowedCounts[$key] = 0 }
        $allowedCounts[$key]++
    }

    $currentCounts = @{}
    foreach ($declaration in @($Violation.Declarations)) {
        $key = [string] $declaration
        if (-not $currentCounts.ContainsKey($key)) { $currentCounts[$key] = 0 }
        $currentCounts[$key]++
    }

    foreach ($key in $currentCounts.Keys) {
        if (-not $allowedCounts.ContainsKey($key) -or $currentCounts[$key] -gt $allowedCounts[$key]) { return $false }
    }

    if ($Violation.HasFileNameMismatch -and -not [bool] $Allowance.allowFileNameMismatch) { return $false }
    return $true
}

$sourceFiles = @(Get-CSharpSourceFiles -RootPath $repoRootFull)
if ($sourceFiles.Count -eq 0) {
    Write-Host 'C# source-layout check skipped: no C# source files found.'
    return
}

Import-RoslynAssemblies
$violations = @(Get-CSharpLayoutViolations -RootPath $repoRootFull -Files $sourceFiles)
$allowanceFullPath = if ([System.IO.Path]::IsPathRooted($AllowancePath)) {
    [System.IO.Path]::GetFullPath($AllowancePath)
}
else {
    [System.IO.Path]::GetFullPath((Join-Path -Path $repoRootFull -ChildPath $AllowancePath))
}

if ($WriteAllowance) {
    if ($violations.Count -eq 0) {
        if (Test-Path -LiteralPath $allowanceFullPath -PathType Leaf) {
            if ($PSCmdlet.ShouldProcess($allowanceFullPath, 'Remove obsolete empty C# source-layout allowance')) {
                Remove-Item -LiteralPath $allowanceFullPath -Force
            }
        }
        Write-Host 'C# source layout is already strict; no allowance file is needed.'
        return
    }

    $document = [ordered]@{
        schemaVersion = 1
        generatedAtUtc = [DateTime]::UtcNow.ToString('o')
        files = @($violations | Sort-Object Path | ForEach-Object {
            [ordered]@{
                path = $_.Path
                declarations = @($_.Declarations)
                allowFileNameMismatch = [bool] $_.HasFileNameMismatch
            }
        })
    }
    $json = $document | ConvertTo-Json -Depth 16
    if ($PSCmdlet.ShouldProcess($allowanceFullPath, 'Write C# source-layout migration allowance')) {
        New-Item -ItemType Directory -Path (Split-Path -Path $allowanceFullPath -Parent) -Force | Out-Null
        Set-Content -LiteralPath $allowanceFullPath -Value $json -Encoding utf8
    }
    Write-Host "Recorded $($violations.Count) existing C# source-layout violation(s): $allowanceFullPath"
    return
}

$allowances = Read-CSharpLayoutAllowance -Path $allowanceFullPath
$failures = [System.Collections.Generic.List[string]]::new()
foreach ($violation in $violations) {
    $allowance = $allowances[$violation.Path]
    if ($null -ne $allowance -and (Test-CSharpViolationAllowed -Violation $violation -Allowance $allowance)) {
        continue
    }

    $details = @()
    if ($violation.Declarations.Count -gt 1) { $details += "$($violation.Declarations.Count) top-level declarations" }
    if ($violation.HasFileNameMismatch) { $details += 'filename does not match every top-level declaration' }
    $failures.Add("$($violation.Path): $($details -join '; ') [$($violation.Declarations -join ', ')]")
}

if ($failures.Count -gt 0) {
    throw "C# source-layout check failed:$([Environment]::NewLine) - $($failures -join "$([Environment]::NewLine) - ")"
}

Write-Host "C# source-layout check passed. Files checked: $($sourceFiles.Count). Active grandfathered violations: $($violations.Count)."
