using System.Collections.Generic;
using TaleWorlds.CampaignSystem;

namespace YL.Prisoners.LordsGrantInfluence
{
    /// <summary>
    /// Calculates the daily influence generated by unique imprisoned Bannerlord heroes who are lords.
    /// </summary>
    /// <remarks>
    /// The calculator deliberately knows nothing about where prisoners are stored. Separating custody discovery
    /// from the 1/2/3 influence policy keeps the gameplay rule easy to test and prevents UI integration concerns
    /// from leaking into the rule itself.
    /// </remarks>
    public interface IImprisonedLordInfluenceCalculator
    {
        /// <summary>
        /// Calculates the complete category-by-category influence breakdown for a set of imprisoned heroes.
        /// </summary>
        /// <param name="imprisonedHeroes">
        /// Heroes currently held by the player clan. Duplicate hero references are permitted; the calculator
        /// deduplicates them so one lord can never grant influence twice in the same calculation.
        /// </param>
        /// <returns>A breakdown containing counts, category subtotals, and the complete daily influence total.</returns>
        ImprisonedLordInfluenceBreakdown CalculateBreakdown(IEnumerable<Hero> imprisonedHeroes);

        /// <summary>
        /// Calculates only the combined daily influence for a set of imprisoned heroes.
        /// </summary>
        /// <param name="imprisonedHeroes">Heroes whose prisoner influence should be evaluated.</param>
        /// <returns>The sum of the three prisoner-tier subtotals.</returns>
        /// <remarks>
        /// This convenience method exists for callers that only need the number. It delegates to
        /// <see cref="CalculateBreakdown"/> so there is still only one source of truth for the policy.
        /// </remarks>
        float CalculateDailyInfluence(IEnumerable<Hero> imprisonedHeroes);

        /// <summary>
        /// Returns the daily influence value for one hero according to the module's highest-tier-only rule.
        /// </summary>
        /// <param name="imprisonedHero">The hero to classify.</param>
        /// <returns>
        /// Three for a kingdom ruler, two for another clan leader, one for another lord, or zero for a hero who
        /// is not a lord.
        /// </returns>
        float GetDailyInfluence(Hero imprisonedHero);
    }
}
